const Posts = [
  {
    id: 1,
    slug: "digital-u",
    title: "Digital U",
    category: "Digital U",
    link: "/",
    date: "2020-05-01",
    description: "This is a very brief description",
    image: "https://source.unsplash.com/random",
  },
  {
    id: 2,
    slug: "tailwind-css",
    title: "Tailwind CSS",
    category: "Development",
    link: "https://digitalu.af.mil",
    date: "2020-05-01",
    description: "This is a very brief description",
    image: "https://source.unsplash.com/random",
  },
  {
    id: 3,
    slug: "mahler's-9th",
    title: "Mahler's 9th",
    category: "Music",
    link: "/",
    date: "2020-05-01",
    description: "This is a very brief description",
    image: "https://source.unsplash.com/random",
  },
  {
    id: 4,
    slug: "recommender-systems",
    title: "Recommender Systems",
    category: "AI/ML",
    link: "/",
    date: "2020-05-01",
    description: "This is a very brief description",
    image: "https://source.unsplash.com/random",
  },
  {
    id: 5,
    slug: "placeholder",
    title: "Placeholder",
    category: "Education",
    link: "/",
    date: "2020-05-01",
    description: "This is a very brief description",
    image: "https://source.unsplash.com/random",
  },
  {
    id: 6,
    slug: "placeholder",
    title: "Placeholder",
    category: "Education",
    link: "/",
    date: "2020-05-01",
    description: "This is a very brief description",
    image: "https://source.unsplash.com/random",
  },
  {
    id: 7,
    slug: "placeholder",
    title: "Placeholder",
    category: "Education",
    link: "/",
    date: "2020-05-01",
    description: "This is a very brief description",
    image: "https://source.unsplash.com/random",
  },
];

export default Posts;
